### ISSUE TITLE
[Bug] Color coding should be reversed in the "SLI Values" graph

### ISSUE THREAD

**Issue by jayakody** [runwhen-contrib/runwhen-beta-issues#1]
**Observation** 
Color coding should be reversed between "BLUE" & "RED" values in the "SLI Values" graph. As you noticed in the attached screenshot >90% values are marked as Blue, and ~70% values are marked as Red. Ideally, these colors should be reversed. 

**Suspected Root Cause** 

**Short Term Ideas**

**Long Term Ideas** 

**Housekeeping  - Check off all before closing issue**
- [ ] This bug is fixed with the short term ideas
- [ ] Long term backlog items are created **and** linked to this issue
![Screen Shot 2022-08-16 at 10 17 17 AM](https://user-images.githubusercontent.com/6126932/184940301-9c8d3a43-c9ac-49d0-b4fb-ddfae414d267.png)

- [ ] The long term backlog items are assigned to the appropriate project

**Comment by more-dinner** [comment]
@jayakody - are you OK if we go in to your workspace in the next few days to make some changes to your SLOs as part of this fix?

### Context
The SLO configuration we have now optimizes for users who want to write their own complex promql queries, e.g. store the SLI as a simple counter (say http requests) and the SLO as a complex query (e.g.  calculating rates, averages over time, top deciles across a fleet).  In i) our own use, ii) expert SREs using our platform, iii) beta users, the emerging best practice is to put any complex calculation in the SLI and keep the SLO query very, very simple.

### Conclusion
The SLI/SLO chart you referenced currently has a "not yet implemented" stub in the way it parses arbitrary queries to display red vs blue colors.  We're going to make the common case a single query with a few more template parameters rather than arbitrary queries, and render the chart colors based on parsing the parameters rather than parsing the query.  It involves moving your slo.yaml files over to the new templated query...  a minor change, and one we can do for you with your permission.

### Even More Context
We may switch out the charting library along the way for various reasons, including bringing in one that more easily supports the panning/zooming feature you requested in #2.

**Comment by more-dinner** [comment]
Closing as part of clean up.  This came out in the 1H Sept sprint, though the scope is limited to slo.yaml formats that follow the v1 spec (i.e. that have an operand key).  UI-created SLOs since the 1H Sept sprint are on this format, so it is only the older ones that we haven't converted over by script or manually will see this issue going forward.
